version: "3.4"
services:

  php-fpm:
    build:
      context: ./docker
      dockerfile: Dockerfile
    volumes:
      - '.:/var/www/html/marketplace'
      - './docker/www.conf:/etc/php/7.4/fpm/pool.d/www.conf'
    networks:
      - nginx

  nginx:
    image: 'nginx:alpine'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '.:/var/www/html/marketplace'
      - './docker/default.conf:/etc/nginx/conf.d/default.conf'
    networks:
      - nginx


  mariadb:
    image: 'mysql:8.0.31'
    ports:
      - '33061:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'yousef'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: 'marketplace'
      MYSQL_USER: 'yousef'
      MYSQL_PASSWORD: 'yousef'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - 'mariadb:/var/lib/mysql'
    networks:
      - nginx
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-pyousef" ]
      retries: 3
      timeout: 5s


  redis:
    image: 'redis:latest'
    container_name: 'marketplaceRedis'
    restart: unless-stopped
    tty: true
    ports:
      - '63792:6379'
    volumes:
      - 'redis:/data'
    networks:
      - nginx

networks:
  nginx:
    driver: bridge
volumes:
  mariadb:
    driver: local
  redis:
    driver: local
